CREATE DATABASE BD_MATRICULAS;
USE BD_MATRICULAS;

CREATE TABLE TB_ALUMNO(
    ID INT PRIMARY KEY NOT NULL,
    MATRICULA VARCHAR(45),
    NOMBRE VARCHAR(45),
    APELLIDO VARCHAR(45),
    LOCALIDAD VARCHAR(45),
    FECHA_NACIMIENTO DATE,
)

CREATE TABLE TB_CURSO(
    ID INT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
)

CREATE TABLE TB_ALUMNO_CURSO(
    ID_ALUMNO INT,
    ID_CURSO INT,
    PRIMARY KEY(ID_ALUMNO, ID_CURSO),
    CONSTRAINT FK_MANY_ALUMNO FOREIGN KEY(ID_ALUMNO)
    REFERENCES TB_ALUMNO(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_MANY_CURSO FOREIGN KEY(ID_CURSO)
    REFERENCES TB_CURSO(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
)


EXEC sp_RENAME 'TB_ALUMNO.LOCALIDAD', 'DIRECCION';

ALTER TABLE TB_ALUMNO
ALTER COLUMN DIRECCION VARCHAR(200);

ALTER TABLE TB_ALUMNO
ADD PAIS VARCHAR(50) NOT NULL;

ALTER TABLE TB_CURSO
ADD CONSTRAINT NOMBRE_UNIQUE UNIQUE(NOMBRE);

ALTER TABLE TB_ALUMNO
ADD CONSTRAINT MATRICULA_UNIQUE UNIQUE(MATRICULA);

SELECT TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'TB_ALUMNO_CURSO';

SELECT TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'TB_ALUMNO';

SELECT TABLE_NAME, CONSTRAINT_TYPE, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'TB_CURSO';

ALTER TABLE TB_ALUMNO_CURSO
DROP CONSTRAINT FK_MANY_ALUMNO, FK_MANY_CURSO

ALTER TABLE TB_ALUMNO
DROP CONSTRAINT PK__TB_ALUMN__3214EC27179CDB9A;


ALTER TABLE TB_CURSO
DROP CONSTRAINT PK__TB_CURSO__3214EC27F52F2033;

ALTER TABLE TB_ALUMNO
DROP COLUMN ID

ALTER TABLE TB_CURSO
DROP COLUMN ID

ALTER TABLE TB_ALUMNO
ADD ID INT PRIMARY KEY NOT NULL IDENTITY(1,1);


ALTER TABLE TB_CURSO
ADD ID INT PRIMARY KEY NOT NULL IDENTITY(1,1);

ALTER TABLE TB_ALUMNO_CURSO
ADD CONSTRAINT FK_MANY_ALUMNO FOREIGN KEY(ID_ALUMNO)
    REFERENCES TB_ALUMNO(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT FK_MANY_CURSO FOREIGN KEY(ID_CURSO)
    REFERENCES TB_CURSO(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

ALTER TABLE TB_CURSO
ALTER COLUMN NOMBRE VARCHAR(100);

DELETE FROM TB_ALUMNO;
DELETE FROM TB_CURSO;
DELETE FROM TB_ALUMNO_CURSO;
DBCC CHECKIDENT ('TB_ALUMNO', RESEED, 0);
DBCC CHECKIDENT ('TB_CURSO', RESEED, 0);
SELECT * FROM TB_ALUMNO;
SELECT * FROM TB_CURSO;
SELECT * FROM TB_ALUMNO_CURSO;
SELECT * FROM TB_ALUMNO_CURSO WHERE ID_ALUMNO = '36'
DROP DATABASE BD_MATRICULAS;

-- INSERT INTO TB_ALUMNO_CURSO(ID_ALUMNO, ID_CURSO) VALUES(25, 25)



SELECT CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO) AS NOMBRE_COMPLETO, CURSO.NOMBRE AS NOMBRE_CURSO
FROM TB_ALUMNO ALUMNO
JOIN TB_ALUMNO_CURSO ALUMNO_CURSO
ON ALUMNO.ID = ALUMNO_CURSO.ID_ALUMNO
JOIN TB_CURSO CURSO
ON CURSO.ID = ALUMNO_CURSO.ID_CURSO
ORDER BY CURSO.NOMBRE

SELECT CURSO.NOMBRE, COUNT(ALUMNO_CURSO.ID_CURSO) AS [ALUMNOS MATRICULADOS]
FROM TB_CURSO CURSO
JOIN TB_ALUMNO_CURSO ALUMNO_CURSO
ON CURSO.ID = ALUMNO_CURSO.ID_CURSO
GROUP BY CURSO.NOMBRE
ORDER BY COUNT(CURSO.NOMBRE) DESC

SELECT CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO) AS NOMBRE_COMPLETO, CURSO.NOMBRE AS NOMBRE_CURSO
FROM TB_ALUMNO ALUMNO
JOIN TB_ALUMNO_CURSO ALUMNO_CURSO
ON ALUMNO.ID = ALUMNO_CURSO.ID_ALUMNO
JOIN TB_CURSO CURSO
ON CURSO.ID = ALUMNO_CURSO.ID_CURSO
WHERE ALUMNO.APELLIDO LIKE '%Gonzalez Narváez%';

SELECT CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO) AS NOMBRE_COMPLETO,  
COUNT(ALUMNO_CURSO.ID_CURSO) AS [CURSOS MATRICULADOS] 
FROM TB_ALUMNO ALUMNO 
JOIN TB_ALUMNO_CURSO ALUMNO_CURSO ON ALUMNO.ID = ALUMNO_CURSO.ID_ALUMNO 
JOIN TB_CURSO CURSO ON CURSO.ID = ALUMNO_CURSO.ID_CURSO 
GROUP BY CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO) 
ORDER BY COUNT(ALUMNO_CURSO.ID_CURSO) DESC;

SELECT ALUMNO.ID, CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO) AS NOMBRE_COMPLETO,  CURSO.NOMBRE 
FROM TB_ALUMNO ALUMNO 
JOIN TB_ALUMNO_CURSO ALUMNO_CURSO 
ON ALUMNO.ID = ALUMNO_CURSO.ID_ALUMNO 
JOIN TB_CURSO CURSO 
ON CURSO.ID = ALUMNO_CURSO.ID_CURSO 
WHERE ALUMNO.APELLIDO LIKE '%Escamilla Fernandez%'
ORDER BY CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO)


SELECT CONCAT(ALUMNO.NOMBRE,' ',ALUMNO.APELLIDO) AS NOMBRE_COMPLETO
FROM TB_ALUMNO ALUMNO 
JOIN TB_ALUMNO_CURSO ALUMNO_CURSO 
ON ALUMNO.ID = ALUMNO_CURSO.ID_ALUMNO 
JOIN TB_CURSO CURSO 
ON CURSO.ID = ALUMNO_CURSO.ID_CURSO 
WHERE CURSO.ID = 25;

